{% set name = "diskcache" %}
{% set version = "5.6.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c3a3fa2743d8535d832ec61c2054a1641f41775aa7c556758a109941e33e4fc

build:
  number: 0
  skip: true #[py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - diskcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.grantjenks.com/docs/diskcache/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Disk and file backed cache.
  description: |
    Diskcache is a fast, persistent, disk-based cache for Python objects.
  dev_url: https://github.com/grantjenks/python-diskcache
  doc_url: https://www.grantjenks.com/docs/diskcache/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
