{% set name = "diskcache" %}
{% set version = "5.0.3" %}
{% set bundle = "tar.gz" %}
{% set hash = "5f4bc2018d653a1d7bbdcdecce45ea12061bf8d3b5f0323b7a5402054a285c52" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - diskcache

about:
  home: http://www.grantjenks.com/docs/diskcache/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Disk and file backed cache.
  dev_url: https://github.com/grantjenks/python-diskcache
  doc_url: http://www.grantjenks.com/docs/diskcache/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
