{% set name = "diskcache" %}
{% set version = "3.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "e7bbbdff3f31bbbda0dffd4c9670e33919b0f069585e48b5b7c6d6c8acdc3a68" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - diskcache

about:
  home: http://www.grantjenks.com/docs/diskcache/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Disk and file backed cache.'
  dev_url: https://github.com/grantjenks/python-diskcache
  doc_url: http://www.grantjenks.com/docs/diskcache/

extra:
  recipe-maintainers:
    - pmlandwehr
