travis:
  secure:
    BINSTAR_TOKEN: A9GYmUDPNKFst56PjlOEHUlpEcS4+BLKlMJgW2ILQCx4MERJ4BIfDo8SeKUL4jIl2xll3iUzHXM51K9/wLViajDL4s2RRydQ/6wJpHFx59GCk+NWEekCJfTJOO7/WA/CpHnvdfqF16LYS7m2rtTxv6Bu8PjNoJZww6vxeUtCV633OJ/15jOWziHCyI6UAOdscLtuPq6hsUG6qveFjRLl4IPVJ1KNToHB/T5EE27GuF0ayeg7jdDWTzfOFy8pz0yCXngIpu8GDbSvQONROWKWL19ePAg+qwXSdKMRIerI9nLO457p0gBLvDn8cuep+LkIrp0h41MJRqh7sw7+FukYMXZlLNqMwr+cL58qp86f3XCuh+wmL87AyRARQfmf7wG8RRDkGDYgwL1PulX4B6WLq8sFO+jY45Fjl7h+G9TBBjG3a4qUg9f2dSr7u7FJ4KbpiGvhzAW9hNYTot95Au6Bf8QZblS6FabxIXMxo21vHqAiof0KMKX7RDFscOlX+HoqY2TRIZcLx0nao1FVXbSLAnr7UYGg8vtTTiiS4TEkoa1ExnEBlHNnhkwZ6n2FX1fihGpL6poAe9N4zxh9c0D3UJW1lyUokXLrlUxwDyWPMdH3NCNlnSAowaH+dybtXwZDHtJvmHUmv1rg28mgxYqTC/3f8ADZHTtOUaQg4MFGjJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
