travis:
  secure:
    BINSTAR_TOKEN: cImWipChIVzwcPU/HbkT2UcpKifWwJSKq5UDc5E6LMhdpuKuxwZeibnAh3mp+6oFKRY+qv0HBfQW1gHnT+fwWaFq7YzZpb2pMeHDh29izDi9fjhm2EJpilU7GU1HwamuXXwB71OQQpOPkRAudmITwRuAmkVQoCMHfFR+cl9epSfcZhT5zBkoidxfv1LO1QjGGTa/RP4/kMhX1s5OD8ezmnduP6I4AYghEpgWa7HhJBFwIqRFatwSDPgjmLWNEyZByLtmJwAn5MVCH9/TGX0ZKrg5Nue+aq1QpmsXNgvlktVjLv4HDr83QFePxJ+uQR7tozzajQg1fy0W9BTBB/Lxw1/LVwnp4BTkGeTXnBDah8WezEuKN9M75cs9nWxq2WDUR5G5gzYJ2/6W1kbwUzQ6ePNyZUudRJ1OOu9dtZ05MVBJqw2B0Tj3JqE9/SJmHuXCdnAJeWrrX23BRLCacS5MTNN/vSNTlHF/i6ujJtvPFc1XqCWwqWqbvIhuMS8rPj8kDeoXLdBbp4H84k6la2fdKz4sxjlJ6XNLx4tubvA4ZqvdiLUL8zsETdiIXZJCvaSQe4eVaPbPyonoKOdiFC/ScnUGDgJbnhJNbNBZOpT9Qpc0XfV9SweTU9Nz7Mjy/wZZoTEyT0tlMtRa7mX35i8Ixlqid+mOx65p1pRpLwINfRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
